In [ ]:
############CHARGEMENT DU CSV ET TABLEAU DE DESCRIPTION DES COLONNES########

# Chargement du CSV et vue des 5 premières lignes
import pandas as pd
df = pd.read_csv("../data/thelook_fr_women_2023_2024.csv")
df.head()

,order_id,order_item_id,product_id,item_created_at,item_status,sale_price,cost,category,department,brand,product_name,order_status,order_created_at,shipped_at,delivered_at,user_id,gender,country,state,city
0,19425,28112,6983,2023-01-01 06:18:03+00:00,Shipped,29.500000,16.048000,Shorts,Women,Fox,Fox Juniors Momentum Short,Shipped,2022-12-29 10:00:00+00:00,2022-12-30 11:29:00+00:00,NaN,15644,F,France,Centre-Val de Loire,Corquilleroy
1,19425,28113,10597,2023-01-01 06:44:58+00:00,Shipped,20.000000,10.000000,Intimates,Women,Wacoal,Wacoal Women's B-Smooth Bralette,Shipped,2022-12-29 10:00:00+00:00,2022-12-30 11:29:00+00:00,NaN,15644,F,France,Centre-Val de Loire,Corquilleroy
2,4710,6730,11792,2023-01-03 04:44:50+00:00,Complete,38.000000,18.468000,Intimates,Women,American Apparel,American Apparel Striped Chiffon Tank,Complete,2023-01-03 08:12:00+00:00,2023-01-03 09:14:00+00:00,2023-01-04 03:03:00+00:00,3853,F,France,Île-de-France,Paris
3,16618,24006,329,2023-01-03 15:13:39+00:00,Complete,27.990000,16.402140,Tops & Tees,Women,Tri-Mountain,Tri-Mountain Women's 3/4-Sleeve Pique Knit Pol...,Complete,2023-01-03 18:58:00+00:00,2023-01-05 13:23:00+00:00,2023-01-09 10:25:00+00:00,13422,F,France,Hauts-de-France,Comines
4,4710,6731,5295,2023-01-05 06:43:09+00:00,Complete,56.880001,29.577601,Pants & Capris,Women,Lauren by Ralph Lauren,Lauren Ralph Lauren Velour Pants,Complete,2023-01-03 08:12:00+00:00,2023-01-03 09:14:00+00:00,2023-01-04 03:03:00+00:00,3853,F,France,Île-de-France,Paris

In [ ]:
import sys
from pathlib import Path
sys.path.append(str(Path("../src").resolve()))
from utils import exemple_valeurs_dataset
# Définitions des colonnes
definitions = [
    "Identifiant unique de la commande. Une commande peut contenir plusieurs produits.",
    "Identifiant unique d'une ligne de commande (un produit dans une commande). Chaque produit commandé possède son propre identifiant.",
    "Identifiant unique du produit vendu. Permet de relier les ventes aux informations du produit.",
    "Date et heure de création de la ligne de commande (ajout du produit à la commande).",
    "État de la ligne de commande (par exemple : Shipped,Complete,Processing,Returned,Cancelled).",
    "Prix de vente du produit payé par le client.",
    "Coût d'achat ou de revient du produit pour l'entreprise. Sert au calcul de la marge.",
    "Catégorie commerciale du produit (ex. : Jeans, Shorts, Accessories).",
    "Département ou grande famille de produits (ex. : Women).",
    "Marque du produit. Certaines valeurs peuvent être manquantes.",
    "Nom descriptif du produit.",
    "Statut global de la commande (Shipped,Complete,Processing,Returned,Cancelled). Contrairement à item_status, il concerne la commande entière.",
    "Date et heure de création de la commande.",
    "Date et heure d'expédition de la commande. Les valeurs manquantes indiquent généralement que la commande n'a pas encore été expédiée ou a été annulée.",
    "Date et heure de livraison au client. Les valeurs manquantes peuvent signifier que la commande est encore en cours de livraison, annulée ou retournée.",
    "Identifiant unique du client ayant passé la commande.",
    "Sexe du client (Male/Female).",
    "Pays de résidence du client.",
    "État, province ou région du client.",
    "Ville de résidence du client."
]

# Types de variables
types_variables = [
    "Identifiant",
    "Identifiant",
    "Identifiant",
    "Date/Heure",
    "Variable catégorielle",
    "Variable numérique",
    "Variable numérique",
    "Variable catégorielle",
    "Variable catégorielle",
    "Variable catégorielle",
    "Texte",
    "Variable catégorielle",
    "Date/Heure",
    "Date/Heure",
    "Date/Heure",
    "Identifiant",
    "Variable catégorielle",
    "Variable catégorielle",
    "Variable catégorielle",
    "Variable catégorielle"
]

# Création du tableau descriptif des colonnes du dataset.
description_df = pd.DataFrame({
    "colonne": df.columns,
    "définition": definitions,
    "type de variable": types_variables,
    "type de donnée": df.dtypes.astype(str).values,
    "exemple": exemple_valeurs_dataset(df)
})
# Ligne pour éviter de tronquer les colonnes de texte dans l'affichage du DataFrame
pd.set_option("display.max_colwidth", None)
# Affichage
description_df

,colonne,définition,type de variable,type de donnée,exemple
0,order_id,Identifiant unique de la commande. Une commande peut contenir plusieurs produits.,Identifiant,int64,19425
1,order_item_id,Identifiant unique d'une ligne de commande (un produit dans une commande). Chaque produit commandé possède son propre identifiant.,Identifiant,int64,28112
2,product_id,Identifiant unique du produit vendu. Permet de relier les ventes aux informations du produit.,Identifiant,int64,6983
3,item_created_at,Date et heure de création de la ligne de commande (ajout du produit à la commande).,Date/Heure,str,2023-01-01 06:18:03+00:00
4,item_status,"État de la ligne de commande (par exemple : Shipped,Complete,Processing,Returned,Cancelled).",Variable catégorielle,str,Shipped
5,sale_price,Prix de vente du produit payé par le client.,Variable numérique,float64,29.5
6,cost,Coût d'achat ou de revient du produit pour l'entreprise. Sert au calcul de la marge.,Variable numérique,float64,16.048
7,category,"Catégorie commerciale du produit (ex. : Jeans, Shorts, Accessories).",Variable catégorielle,str,Shorts
8,department,Département ou grande famille de produits (ex. : Women).,Variable catégorielle,str,Women
9,brand,Marque du produit. Certaines valeurs peuvent être manquantes.,Variable catégorielle,str,Fox
10,product_name,Nom descriptif du produit.,Texte,str,Fox Juniors Momentum Short
11,order_status,"Statut global de la commande (Shipped,Complete,Processing,Returned,Cancelled). Contrairement à item_status, il concerne la commande entière.",Variable catégorielle,str,Shipped
12,order_created_at,Date et heure de création de la commande.,Date/Heure,str,2022-12-29 10:00:00+00:00
13,shipped_at,Date et heure d'expédition de la commande. Les valeurs manquantes indiquent généralement que la commande n'a pas encore été expédiée ou a été annulée.,Date/Heure,str,2022-12-30 11:29:00+00:00
14,delivered_at,"Date et heure de livraison au client. Les valeurs manquantes peuvent signifier que la commande est encore en cours de livraison, annulée ou retournée.",Date/Heure,str,2023-01-04 03:03:00+00:00
15,user_id,Identifiant unique du client ayant passé la commande.,Identifiant,int64,15644
16,gender,Sexe du client (Male/Female).,Variable catégorielle,str,F
17,country,Pays de résidence du client.,Variable catégorielle,str,France
18,state,"État, province ou région du client.",Variable catégorielle,str,Centre-Val de Loire
19,city,Ville de résidence du client.,Variable catégorielle,str,Corquilleroy