In [1]:
############CHARGEMENT DU CSV ET TABLEAU DE DESCRIPTION DES COLONNES########

# Chargement du CSV et vue des 5 premières lignes
import pandas as pd
df = pd.read_csv("../data/thelook_fr_women_2023_2024.csv")
# Nous allons préserver les données brutes et travailler en toute sécurité sur une version modifiable, une copie.
df_copie = df.copy()
df_copie.head()

,order_id,order_item_id,product_id,item_created_at,item_status,sale_price,cost,category,department,brand,product_name,order_status,order_created_at,shipped_at,delivered_at,user_id,gender,country,state,city
0,19425,28112,6983,2023-01-01 06:18:03+00:00,Shipped,29.500000,16.048000,Shorts,Women,Fox,Fox Juniors Momentum Short,Shipped,2022-12-29 10:00:00+00:00,2022-12-30 11:29:00+00:00,NaN,15644,F,France,Centre-Val de Loire,Corquilleroy
1,19425,28113,10597,2023-01-01 06:44:58+00:00,Shipped,20.000000,10.000000,Intimates,Women,Wacoal,Wacoal Women's B-Smooth Bralette,Shipped,2022-12-29 10:00:00+00:00,2022-12-30 11:29:00+00:00,NaN,15644,F,France,Centre-Val de Loire,Corquilleroy
2,4710,6730,11792,2023-01-03 04:44:50+00:00,Complete,38.000000,18.468000,Intimates,Women,American Apparel,American Apparel Striped Chiffon Tank,Complete,2023-01-03 08:12:00+00:00,2023-01-03 09:14:00+00:00,2023-01-04 03:03:00+00:00,3853,F,France,Île-de-France,Paris
3,16618,24006,329,2023-01-03 15:13:39+00:00,Complete,27.990000,16.402140,Tops & Tees,Women,Tri-Mountain,Tri-Mountain Women's 3/4-Sleeve Pique Knit Pol...,Complete,2023-01-03 18:58:00+00:00,2023-01-05 13:23:00+00:00,2023-01-09 10:25:00+00:00,13422,F,France,Hauts-de-France,Comines
4,4710,6731,5295,2023-01-05 06:43:09+00:00,Complete,56.880001,29.577601,Pants & Capris,Women,Lauren by Ralph Lauren,Lauren Ralph Lauren Velour Pants,Complete,2023-01-03 08:12:00+00:00,2023-01-03 09:14:00+00:00,2023-01-04 03:03:00+00:00,3853,F,France,Île-de-France,Paris

In [2]:
import sys
from pathlib import Path
sys.path.append(str(Path("../src").resolve()))
from utils import exemple_valeurs_dataset,valeurs_manquantes_shipped_at_par_statut,valeurs_manquantes_delivered_at_par_statut
# Définitions des colonnes
definitions: list[str] = [
    "Identifiant unique de la commande. Une commande peut contenir plusieurs produits.",
    "Identifiant unique d'une ligne de commande (un produit dans une commande). Chaque produit commandé possède son propre identifiant.",
    "Identifiant unique du produit vendu. Permet de relier les ventes aux informations du produit.",
    "Date et heure de création de la ligne de commande (ajout du produit à la commande).",
    "État de la ligne de commande (par exemple : Shipped,Complete,Processing,Returned,Cancelled).",
    "Prix de vente du produit payé par le client.",
    "Coût d'achat ou de revient du produit pour l'entreprise. Sert au calcul de la marge.",
    "Catégorie commerciale du produit (ex. : Jeans, Shorts, Accessories).",
    "Département ou grande famille de produits (ex. : Women).",
    "Marque du produit. Certaines valeurs peuvent être manquantes.",
    "Nom descriptif du produit.",
    "Statut global de la commande (Shipped,Complete,Processing,Returned,Cancelled). Contrairement à item_status, il concerne la commande entière.",
    "Date et heure de création de la commande.",
    "Date et heure d'expédition de la commande. Les valeurs manquantes indiquent généralement que la commande n'a pas encore été expédiée ou a été annulée.",
    "Date et heure de livraison au client. Les valeurs manquantes peuvent signifier que la commande est encore en cours de livraison, annulée ou retournée.",
    "Identifiant unique du client ayant passé la commande.",
    "Sexe du client (Male/Female).",
    "Pays de résidence du client.",
    "État, province ou région du client.",
    "Ville de résidence du client."
]

# Types de variables
types_variables: list[str] = [
    "Identifiant",
    "Identifiant",
    "Identifiant",
    "Date/Heure",
    "Variable catégorielle",
    "Variable numérique",
    "Variable numérique",
    "Variable catégorielle",
    "Variable catégorielle",
    "Variable catégorielle",
    "Texte",
    "Variable catégorielle",
    "Date/Heure",
    "Date/Heure",
    "Date/Heure",
    "Identifiant",
    "Variable catégorielle",
    "Variable catégorielle",
    "Variable catégorielle",
    "Variable catégorielle"
]

# Création du tableau descriptif des colonnes du dataset.
description_colonnes_dataset_df = pd.DataFrame({
    "colonne": df_copie.columns,
    "définition": definitions,
    "type de variable": types_variables,
    "type de donnée": df_copie.dtypes.astype(str).values,
    "exemple": exemple_valeurs_dataset(df_copie)
})
# Ligne pour éviter de tronquer les colonnes de texte dans l'affichage du DataFrame
pd.set_option("display.max_colwidth", None)
# Affichage
description_colonnes_dataset_df

,colonne,définition,type de variable,type de donnée,exemple
0,order_id,Identifiant unique de la commande. Une commande peut contenir plusieurs produits.,Identifiant,int64,19425
1,order_item_id,Identifiant unique d'une ligne de commande (un produit dans une commande). Chaque produit commandé possède son propre identifiant.,Identifiant,int64,28112
2,product_id,Identifiant unique du produit vendu. Permet de relier les ventes aux informations du produit.,Identifiant,int64,6983
3,item_created_at,Date et heure de création de la ligne de commande (ajout du produit à la commande).,Date/Heure,str,2023-01-01 06:18:03+00:00
4,item_status,"État de la ligne de commande (par exemple : Shipped,Complete,Processing,Returned,Cancelled).",Variable catégorielle,str,Shipped
5,sale_price,Prix de vente du produit payé par le client.,Variable numérique,float64,29.5
6,cost,Coût d'achat ou de revient du produit pour l'entreprise. Sert au calcul de la marge.,Variable numérique,float64,16.048
7,category,"Catégorie commerciale du produit (ex. : Jeans, Shorts, Accessories).",Variable catégorielle,str,Shorts
8,department,Département ou grande famille de produits (ex. : Women).,Variable catégorielle,str,Women
9,brand,Marque du produit. Certaines valeurs peuvent être manquantes.,Variable catégorielle,str,Fox
10,product_name,Nom descriptif du produit.,Texte,str,Fox Juniors Momentum Short
11,order_status,"Statut global de la commande (Shipped,Complete,Processing,Returned,Cancelled). Contrairement à item_status, il concerne la commande entière.",Variable catégorielle,str,Shipped
12,order_created_at,Date et heure de création de la commande.,Date/Heure,str,2022-12-29 10:00:00+00:00
13,shipped_at,Date et heure d'expédition de la commande. Les valeurs manquantes indiquent généralement que la commande n'a pas encore été expédiée ou a été annulée.,Date/Heure,str,2022-12-30 11:29:00+00:00
14,delivered_at,"Date et heure de livraison au client. Les valeurs manquantes peuvent signifier que la commande est encore en cours de livraison, annulée ou retournée.",Date/Heure,str,2023-01-04 03:03:00+00:00
15,user_id,Identifiant unique du client ayant passé la commande.,Identifiant,int64,15644
16,gender,Sexe du client (Male/Female).,Variable catégorielle,str,F
17,country,Pays de résidence du client.,Variable catégorielle,str,France
18,state,"État, province ou région du client.",Variable catégorielle,str,Centre-Val de Loire
19,city,Ville de résidence du client.,Variable catégorielle,str,Corquilleroy

In [3]:
# Regardons les statuts et leurs fréquences pour les colonnes order_status et item_status
print(df_copie["order_status"].value_counts())
print(df_copie["item_status"].value_counts())
# Nous constatons que nous avons les mêmes statuts dans ces deux colonnes; et elles ont les mêmes fréquences d'apparition. Il est important de noter que les statuts "Returned" et "Cancelled" sont présents dans ces deux colonnes, ce qui peut indiquer des comportements de retour ou d'annulation à la fois au niveau de la commande globale et au niveau des lignes de commande individuelles.

order_status
Shipped       497
Complete      425
Processing    306
Cancelled     240
Returned      211
Name: count, dtype: int64
item_status
Shipped       497
Complete      425
Processing    306
Cancelled     240
Returned      211
Name: count, dtype: int64

In [4]:
# Définition des statuts utilisés pour order_status et item_status

#Statuts
statuts: list[str] = [
    "Shipped",
    "Complete",
    "Processing",
    "Returned",
    "Cancelled"
]
# Définition des statuts
descriptions_statuts: list[str] = [
    "La commande a été expédiée par le vendeur et est en cours d'acheminement vers le client. Elle n'a pas encore été livrée.",
    "La commande a été livrée avec succès et le processus de vente est terminé. C'est généralement une vente finalisée.",
    "La commande est en cours de traitement (préparation, vérification du paiement, emballage, etc.) mais n'a pas encore été expédiée.",
    "La commande a été retournée par le client après la livraison. Selon les règles du vendeur, elle peut donner lieu à un remboursement ou à un échange.",
    "La commande a été annulée avant d'être finalisée. Elle n'a généralement pas été expédiée. L'annulation peut venir du client, du vendeur ou être due à un problème de paiement ou de stock."
]
# Dataframe du descriptif des statuts 
df_descriptions_statuts = pd.DataFrame({
    "statut de commande": statuts,
    "description du statut": descriptions_statuts
})

# Affichage du tableau descriptif des statuts 
df_descriptions_statuts

,statut de commande,description du statut
0,Shipped,La commande a été expédiée par le vendeur et est en cours d'acheminement vers le client. Elle n'a pas encore été livrée.
1,Complete,La commande a été livrée avec succès et le processus de vente est terminé. C'est généralement une vente finalisée.
2,Processing,"La commande est en cours de traitement (préparation, vérification du paiement, emballage, etc.) mais n'a pas encore été expédiée."
3,Returned,"La commande a été retournée par le client après la livraison. Selon les règles du vendeur, elle peut donner lieu à un remboursement ou à un échange."
4,Cancelled,"La commande a été annulée avant d'être finalisée. Elle n'a généralement pas été expédiée. L'annulation peut venir du client, du vendeur ou être due à un problème de paiement ou de stock."

In [5]:
# Nous évoluerons sur les hypothèses suivantes:

# Schéma simplifié de vie d'une ligne de commande : order_created -> processing -> shipped -> complete -> returned (si le client renvoie)

# À tout moment "avant la livraison", la commande peut également devenir "cancelled" (annulée) si le client annule sa commande ou si le vendeur décide de l'annuler.

# Returned : vente annulée après livraison ; elle peut réduire le chiffre d'affaires net si le remboursement est effectué

# Dans notre cas, nous considérons le remboursement éffectué en cas de commande retournée.

In [6]:
# dimensions du DataFrame 
print(df_copie.shape)
# Informations générales sur le DataFrame
print(df_copie.info())

(1679, 20)
<class 'pandas.DataFrame'>
RangeIndex: 1679 entries, 0 to 1678
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1679 non-null   int64
 1   order_item_id     1679 non-null   int64
 2   product_id        1679 non-null   int64
 3   item_created_at   1679 non-null   str
 4   item_status       1679 non-null   str
 5   sale_price        1679 non-null   float64
 6   cost              1679 non-null   float64
 7   category          1679 non-null   str
 8   department        1679 non-null   str
 9   brand             1677 non-null   str
 10  product_name      1679 non-null   str
 11  order_status      1679 non-null   str
 12  order_created_at  1679 non-null   str
 13  shipped_at        1133 non-null   str
 14  delivered_at      636 non-null    str
 15  user_id           1679 non-null   int64
 16  gender            1679 non-null   str
 17  country           1679 non-null   str
 18  state             1679 non-null   str
 19  city              1679 non-null   str
dtypes: float64(2), int64(4), str(14)
memory usage: 262.5 KB
None

In [7]:
###############################CONTROLE DE QUALITE#####################
# Valeurs manquantes par colonne
df_copie.isnull().sum()

order_id               0
order_item_id          0
product_id             0
item_created_at        0
item_status            0
sale_price             0
cost                   0
category               0
department             0
brand                  2
product_name           0
order_status           0
order_created_at       0
shipped_at           546
delivered_at        1043
user_id                0
gender                 0
country                0
state                  0
city                   0
dtype: int64

In [8]:
# La colonne brand  est une variable catégorielle qui a 2 valeurs manquantes; nous ne pouvons pas les remplacer par une modalité car la modalité la plus fréquente a un taux de présence 6% (qui est <50%); calcul fait avec : df["brand"].value_counts(normalize=True)*100. Aussi, nous ne devons pas supprimer les lignes/colonnes correspondantes au risque de perdre des informations. Nous choisissons de les imputer par "unknown".
df_copie["brand"]=df_copie['brand'].fillna("unknown")

In [9]:
# La colonne shipped_at indique la date d'expédition. Une valeur manquante signifie souvent que la commande est: soit encore en cours de traitement (Processing) ou a été annulée (Cancelled) ; 
# Regardons de plus près avec les statuts (order_status) correspondants à ces valeurs manquantes.
valeurs_manquantes_shipped_at_par_statut(df_copie)
# Le tableau ci-dessous montre que les valeurs manquantes de shipped_at sont principalement associées aux statuts Processing(306) et Cancelled(240); et on a 546=306+240. Cela confirme que les commandes avec des valeurs manquantes dans shipped_at sont soit en cours de traitement, soit annulées. Il est donc logique de conserver ces valeurs manquantes; car elles reflètent l'état réel des commandes. Pour les autres statuts, il n'y a pas de valeurs manquantes, ce qui indique que les commandes ont été expédiées ou livrées avec succès.

      Order_Status  Nbre_valeurs_manquantes_shipped_at
0       Processing                                 306
1          Shipped                                   0
2        Completed                                   0
3        Cancelled                                 240
4         Returned                                   0
5  Statut Manquant                                   0

In [10]:
# La colonne delivered_at indique la date de livraison. Une valeur manquante signifie généralement que la commande n'a pas encore été livrée : elle est soit encore en cours de traitement (Processing), soit en cours d'acheminement (Shipped), soit elle a été annulée (Cancelled)
# Regardons de plus près avec les statuts (order_status) correspondants à ces valeurs manquantes. 
valeurs_manquantes_delivered_at_par_statut(df_copie)
# Le tableau ci-dessous montre que les valeurs manquantes de delivered_at sont principalement associées aux statuts Processing(306),Shipped(497) et Cancelled(240); et on a 1043=306+497+240. Cela confirme que les commandes avec des valeurs manquantes dans delivered_at sont soit en cours de traitement (Processing), soit en cours d'acheminement (Shipped), soit  annulées (Cancelled). Il est donc logique de conserver ces valeurs manquantes; car elles reflètent l'état réel des commandes. Pour les autres statuts, il n'y a pas de valeurs manquantes, ce qui indique que les commandes ont été expédiées ou livrées avec succès.

      Order_Status  Nbre_valeurs_manquantes_delivered_at
0       Processing                                   306
1          Shipped                                   497
2        Completed                                     0
3        Cancelled                                   240
4         Returned                                     0
5  Statut Manquant                                     0

In [11]:
# Doublons
df_copie.duplicated().sum()
# L'analyse des doublons à l'aide de df_copie.duplicated().sum() montre qu'aucune ligne n'est dupliquée (0 doublon). Aucun traitement de suppression des doublons n'est donc nécessaire

np.int64(0)

In [12]:
# Formats de Dates:
# Nous avons 4 variables date/heure : order_created_at, shipped_at, delivered_at et item_created_at. Nous allons vérifier si elles sont bien au format datetime.
df_copie[["item_created_at","order_created_at","shipped_at","delivered_at"]].dtypes

item_created_at     str
order_created_at    str
shipped_at          str
delivered_at        str
dtype: object

In [13]:
# Le résultat montre que ces colonnes sont actuellement de type object (chaîne de caractères). Pour effectuer des analyses temporelles, il est nécessaire de les convertir en type datetime. Nous allons donc procéder à cette conversion.
colonnes_date = ["item_created_at","order_created_at","shipped_at","delivered_at"]
for i in colonnes_date:
  df_copie[i]=pd.to_datetime(df_copie[i])
  print(f"Le nouveau type de la colonne {i} est {df_copie[i].dtype}")

Le nouveau type de la colonne item_created_at est datetime64[us, UTC]
Le nouveau type de la colonne order_created_at est datetime64[us, UTC]
Le nouveau type de la colonne shipped_at est datetime64[us, UTC]
Le nouveau type de la colonne delivered_at est datetime64[us, UTC]

In [76]:
# Après conversion, vérifions maintenant les cohérences des dates

# Donnons la liste d'années présentes dans les colonnes de dates pour vérifier si elles se situent bien dans le périmètre 2023 - 2024.
from datetime import datetime
print(df_copie["item_created_at"].dt.year.value_counts())
print(df_copie["order_created_at"].dt.year.value_counts())
print(df_copie["shipped_at"].dt.year.value_counts())
print(df_copie["delivered_at"].dt.year.value_counts())

item_created_at
2024    968
2023    711
Name: count, dtype: int64
order_created_at
2024    968
2023    709
2022      2
Name: count, dtype: int64
shipped_at
2024.0    670
2023.0    459
2022.0      2
2025.0      2
Name: count, dtype: int64
delivered_at
2024.0    400
2023.0    234
2025.0      2
Name: count, dtype: int64

In [ ]:
# Nous notons que certaines dates sont de 2022 , 2025, NaN. 

# Nous avons dejà étudié les valeurs manquantes (NaN) dans les colonnes shipped_at et delivered_at. 
# Pour les années 2022 et 2025, il est important de vérifier si elles sont cohérentes avec le contexte de l'analyse. Si ces dates sont des erreurs ou des anomalies, nous devrons décider comment les traiter (par exemple, les corriger, les supprimer ou les conserver en fonction de leur impact sur l'analyse).
# Ressortons les "lignes" (correspondantes aux variables date uniquement) qui ont des "dates en 2022 et/ou 2025" pour les examiner de plus près.
df_copie[(df_copie["order_created_at"].dt.year==2022) | (df_copie["shipped_at"].dt.year==2022) | (df_copie["shipped_at"].dt.year==2025) | (df_copie["delivered_at"].dt.year==2025)][["item_created_at","order_created_at","shipped_at","delivered_at"]]

,item_created_at,order_created_at,shipped_at,delivered_at
0,2023-01-01 06:18:03+00:00,2022-12-29 10:00:00+00:00,2022-12-30 11:29:00+00:00,NaT
1,2023-01-01 06:44:58+00:00,2022-12-29 10:00:00+00:00,2022-12-30 11:29:00+00:00,NaT
1661,2024-12-27 04:27:59+00:00,2024-12-27 05:27:00+00:00,2024-12-28 21:46:00+00:00,2025-01-02 00:39:00+00:00
1674,2024-12-31 02:04:52+00:00,2024-12-31 03:27:00+00:00,2025-01-01 08:59:00+00:00,2025-01-02 13:06:00+00:00
1675,2024-12-31 04:28:58+00:00,2024-12-31 05:13:00+00:00,2025-01-02 02:26:00+00:00,NaT

In [ ]:
# Les lignes 1661 , 1674 et 1675 sont des cas normaux:
# 1661: Commande créée fin 2024, expédiée le 28/12/2024, livrée le 02/01/2025.
# 1674: Commande créée le 31/12/2024, expédiée le 01/01/2025, livrée le 02/01/2025.
# 1675: Commande créée le 31/12/2024, expédiée le 02/01/2025, pas encore livrée (NaT).
# Je trouve les lignes 1661 , 1674, et 1675 comme des cas normaux.

In [ ]:
# Les lignes 0 et 1:  item_created_at est en 2023, alors que order_created_at et shipped_at sont en 2022. il est  IMPOSSIBLE qu'un article soit créé après que la commande ait déjà été expédiée.

# Regardons de manière globale s'il n'y a pas des cas similaires:
# Pour se faire,nous allons vérifier si les dates d'expédition (shipped_at) et de livraison (delivered_at) sont postérieures à la date de création de la commande/item (order_created_at/item_created_at). De plus, nous allons aussi vérifier que la date de livraison est postérieure à la date d'expédition. 

# Vérifications si les dates shipped_at sont postérieures aux dates correspondantes item_created_at/order_created
masque_coherence_item_order_and_shipped=(df_copie["item_created_at"]>df_copie["shipped_at"])|(df_copie["order_created_at"]>df_copie["shipped_at"])
masque_coherence_item_order_and_shipped.sum()
# L'output suivant nous montre qu'il y'a plusieurs cas incohérents (365).

np.int64(375)

In [65]:
# L'output suivant nous laisse croire que les cas concernés semblent être dans le même time zone. Donc, nous avons de bonnes raisons d'éliminer la cause time zone.
df_copie[masque_coherence_item_order_and_shipped][["item_created_at","order_created_at","shipped_at","delivered_at"]]

,item_created_at,order_created_at,shipped_at,delivered_at
0,2023-01-01 06:18:03+00:00,2022-12-29 10:00:00+00:00,2022-12-30 11:29:00+00:00,NaT
1,2023-01-01 06:44:58+00:00,2022-12-29 10:00:00+00:00,2022-12-30 11:29:00+00:00,NaT
4,2023-01-05 06:43:09+00:00,2023-01-03 08:12:00+00:00,2023-01-03 09:14:00+00:00,2023-01-04 03:03:00+00:00
15,2023-01-16 10:37:00+00:00,2023-01-15 12:38:00+00:00,2023-01-15 12:47:00+00:00,2023-01-20 07:21:00+00:00
16,2023-01-16 11:01:44+00:00,2023-01-14 11:28:00+00:00,2023-01-16 08:38:00+00:00,NaT
...,...,...,...,...
1657,2024-12-26 08:49:19+00:00,2024-12-22 11:15:00+00:00,2024-12-24 02:28:00+00:00,2024-12-24 08:16:00+00:00
1664,2024-12-27 12:56:45+00:00,2024-12-23 15:56:00+00:00,2024-12-25 06:32:00+00:00,2024-12-26 14:52:00+00:00
1672,2024-12-30 12:07:40+00:00,2024-12-29 14:25:00+00:00,2024-12-30 00:05:00+00:00,2024-12-31 22:07:00+00:00
1673,2024-12-30 13:48:36+00:00,2024-12-29 14:25:00+00:00,2024-12-30 00:05:00+00:00,2024-12-31 22:07:00+00:00
1678,2024-12-31 10:40:48+00:00,2024-12-29 14:25:00+00:00,2024-12-30 00:05:00+00:00,2024-12-31 22:07:00+00:00

In [66]:
# 375 observations présentent une incohérence chronologique entre la création de la commande ou de l'item et la date d'expédition. Ces lignes doivent être examinées avant toute analyse. Creusons encore un peu plus :
masque_coherence_item_order_and_shipped1 = df_copie["item_created_at"] > df_copie["shipped_at"]
masque_coherence_item_order_and_shipped2 = df_copie["order_created_at"] > df_copie["shipped_at"]

print(masque_coherence_item_order_and_shipped1.sum())            
# incohérence item -> shipped
print(masque_coherence_item_order_and_shipped2.sum())            
# incohérence order -> shipped

375
0

In [56]:
# Nous constatons que l'incohérence chronologique est entre la création de l'item et la date d'expédition.

In [82]:
# Vérifications si les dates delivered_at sont postérieures aux dates correspondantes item_created_at/order_created
masque_coherence_item_order_and_delivered=(df_copie["item_created_at"]>df_copie["delivered_at"])|(df_copie["order_created_at"]>df_copie["delivered_at"])
masque_coherence_item_order_and_delivered.sum()

np.int64(63)

In [68]:
# L'output suivant nous laisse croire que les cas concernés semblent être dans le même time zone. Donc, nous avons de bonnes raisons d'éliminer la cause time zone.
df_copie[masque_coherence_item_order_and_delivered][["item_created_at","order_created_at","shipped_at","delivered_at"]]

,item_created_at,order_created_at,shipped_at,delivered_at
4,2023-01-05 06:43:09+00:00,2023-01-03 08:12:00+00:00,2023-01-03 09:14:00+00:00,2023-01-04 03:03:00+00:00
76,2023-02-17 16:10:39+00:00,2023-02-13 18:03:00+00:00,2023-02-15 09:29:00+00:00,2023-02-15 21:15:00+00:00
141,2023-03-28 23:33:50+00:00,2023-03-26 03:23:00+00:00,2023-03-27 04:05:00+00:00,2023-03-27 08:26:00+00:00
142,2023-03-29 01:34:29+00:00,2023-03-26 03:23:00+00:00,2023-03-27 04:05:00+00:00,2023-03-27 08:26:00+00:00
171,2023-04-08 16:18:50+00:00,2023-04-05 16:53:00+00:00,2023-04-06 20:16:00+00:00,2023-04-07 04:06:00+00:00
...,...,...,...,...
1535,2024-11-20 10:56:46+00:00,2024-11-17 14:12:00+00:00,2024-11-17 14:45:00+00:00,2024-11-17 15:29:00+00:00
1562,2024-11-24 16:39:35+00:00,2024-11-20 18:57:00+00:00,2024-11-21 22:17:00+00:00,2024-11-23 01:53:00+00:00
1652,2024-12-24 10:32:17+00:00,2024-12-21 14:17:00+00:00,2024-12-23 00:40:00+00:00,2024-12-23 01:04:00+00:00
1657,2024-12-26 08:49:19+00:00,2024-12-22 11:15:00+00:00,2024-12-24 02:28:00+00:00,2024-12-24 08:16:00+00:00
1664,2024-12-27 12:56:45+00:00,2024-12-23 15:56:00+00:00,2024-12-25 06:32:00+00:00,2024-12-26 14:52:00+00:00

In [81]:
# 63 observations présentent une incohérence chronologique entre la création de la commande ou de l'item et la date de livraison. Ces lignes doivent être examinées avant toute analyse. Creusons encore un peu plus :
masque_coherence_item_order_and_delivered1 = df_copie["item_created_at"] > df_copie["delivered_at"]
masque_coherence_item_order_and_delivered2 = df_copie["order_created_at"] > df_copie["delivered_at"]

print(masque_coherence_item_order_and_delivered1.sum())            
# incohérence item -> shipped
print(masque_coherence_item_order_and_delivered2.sum())            
# incohérence order -> shipped

63
0

In [72]:
# Nous constatons que l'incohérence chronologique est entre la création de l'item et la date de délivrance.

In [86]:
# Vérifions maintenant que la date de livraison est postérieure à la date d'expédition.
masque_coherence_shipped_and_delivered = df_copie["shipped_at"] > df_copie["delivered_at"]
print(masque_coherence_shipped_and_delivered.sum())

0

In [87]:
# En ce qui concerne la cohérence temporelle, il est important d'attirer l'attention sur les faits suivants :
# 2022 : 02 commandes crées et 02 expéditions faites.
# 2025 : 02 expéditions et 02 livraisons faites.
# En ce qui concerne les incohérences :
# 365 créations de lignes de commande (ajouts de produits aux commandes) pour des commandes dejà expédiées. IMPOSSIBLE
# 63 créations de lignes de commande (ajouts de produits aux commandes) pour des commandes dejà livrées. IMPOSSIBLE
# Il est important d'apporter un éclairci à ces incohérences avant de poursuivre l'analyse.

In [88]:
##########################EXPLORATION DESCRIPTIVE#########################

In [ ]:
# Trouvons les proportions des lignes de commande returned et cancelled pour analyses retour et comportements client.

print(df_copie['item_status'].value_counts(normalize=True)*100)
print(df_copie['order_status'].value_counts(normalize=True)*100)

item_status
Shipped       29.600953
Complete      25.312686
Processing    18.225134
Cancelled     14.294223
Returned      12.567004
Name: proportion, dtype: float64
order_status
Shipped       29.600953
Complete      25.312686
Processing    18.225134
Cancelled     14.294223
Returned      12.567004
Name: proportion, dtype: float64

In [ ]:


# Marge=sale_price−cost
# Pour la marge et le chiffre d'affaires net, nous considerons que les commandes annulées (cancelled) et retournées (returned) ne génèrent pas de chiffre d'affaires ni de marge. Pour leurs calculs, nous ne prendrons donc en compte que les commandes complétées (complete) auxquelles nous réduirons les remboursements (returned).  
# Les dates permettent de calculer plusieurs KPI, par exemple :
# délai d'expédition = shipped_at - order_created_at ;
# délai de livraison = delivered_at - shipped_at ;
# temps total de traitement = delivered_at - order_created_at.

# Je trouve entre autres que se sont les colonnes les plus utiles pour notre périmètre métier



#Chaque fois qu'on voudra tenir compte du CA, il faudrait s'assurer de prendre uniquement les valeurs de prix des produits/commandes dejà vendus (item_status=='complete' / order_status=='complete'); nous allons tenir compte de ligne ou commande en fonction du KPI demandé ou ajouté.
#La marge brute peut être calculée par :

#Marge=sale_price−cost
#Les dates permettent de calculer plusieurs KPI, par exemple :
#délai d'expédition = shipped_at - order_created_at ;
#délai de livraison = delivered_at - shipped_at ;
#temps total de traitement = delivered_at - order_created_at.
#Colonnes les plus utiles pour votre périmètre métier

#Si votre objectif est comparer les performances de 2023 à 2024 (CA, marge, retours et comportement client), les colonnes les plus importantes sont :

#Chiffre d'affaires : sale_price, cost,order_created_at, item_created_at,item_status, order_status
#Marge : sale_price, cost
#Retours : item_status, order_status
#Comportement client : user_id, gender, country, state, city
#Segmentation des ventes : category, department, brand, product_name
#Analyse temporelle : order_created_at, shipped_at, delivered_at